drop database cinema;
create database cinema;
use cinema;

-- roles
INSERT INTO `cinema`.`roles` (`name`) VALUES ('ROLE_ADMIN');
INSERT INTO `cinema`.`roles` (`name`) VALUES ('ROLE_USER');

-- users
INSERT INTO `cinema`.`users` (`address`, `email`, `full_name`, `password`, `phone`, `username`) VALUES ('Thủ Đức', 'qhuy1911@gmail.com', 'Quoc Huy', '$2a$10$CmjA.qvo5XzYBkFiR08rBelnh0x503abMg1I78i9PxQEPz64mUkma', '0985115781', 'qhuy1911');
INSERT INTO `cinema`.`users` (`address`, `email`, `full_name`, `password`, `phone`, `username`) VALUES ('Thủ Đức', 'user01@gmail.com', 'Nguyễn Gia Linh', '$2a$10$CmjA.qvo5XzYBkFiR08rBelnh0x503abMg1I78i9PxQEPz64mUkma', '0358798859', 'user01');
INSERT INTO `cinema`.`users` (`address`, `email`, `full_name`, `password`, `phone`, `username`) VALUES ('Tp Hồ Chí Minh', 'user02@gmail.com', 'Lê Nhật Minh', '$2a$10$CmjA.qvo5XzYBkFiR08rBelnh0x503abMg1I78i9PxQEPz64mUkma', '0258978985', 'user02');
INSERT INTO `cinema`.`users` (`address`, `email`, `full_name`, `password`, `phone`, `username`) VALUES ('Bình Thạnh', 'user03@gmail.com', 'Nguyễn Quốc Cường', '$2a$10$CmjA.qvo5XzYBkFiR08rBelnh0x503abMg1I78i9PxQEPz64mUkma', '0358954854', 'user03');

-- user_roles
INSERT INTO `cinema`.`user_roles` (`user_id`, `role_id`) VALUES ('1', '1');
INSERT INTO `cinema`.`user_roles` (`user_id`, `role_id`) VALUES ('1', '2');
INSERT INTO `cinema`.`user_roles` (`user_id`, `role_id`) VALUES ('2', '2');
INSERT INTO `cinema`.`user_roles` (`user_id`, `role_id`) VALUES ('3', '2');
INSERT INTO `cinema`.`user_roles` (`user_id`, `role_id`) VALUES ('4', '2');

-- bookings
INSERT INTO `cinema`.`bookings` (`user_id`) VALUES ('2');
INSERT INTO `cinema`.`bookings` (`user_id`) VALUES ('3');
INSERT INTO `cinema`.`bookings` (`user_id`) VALUES ('4');

-- movies
INSERT INTO `cinema`.`movies` (`description`, `director`, `duration`, `image`, `name`, `start_date`, `trailer`) VALUES ('Bốn năm sau kết thúc Jurassic World: Fallen Kingdom, những con khủng long đã thoát khỏi nơi giam cầm và tiến vào thế giới loài người. Giờ đây, chúng xuất hiện ở khắp mọi nơi. Sinh vật to lớn ấy không còn chỉ ở trên đảo như trước nữa mà gần ngay trước mắt, thậm chí còn có thể chạm tới. Owen Grady may mắn gặp lại cô khủng long mà anh và khán giả vô cùng yêu mến - Blue. Tuy nhiên, Blue không đi một mình mà còn đem theo một chú khủng long con khác. Điều này khiến Owen càng quyết tâm bảo vệ mẹ con cô được sinh sống an toàn. Thế nhưng, hai giống loài quá khác biệt. Liệu có thể tồn tại một kỷ nguyên mà khủng long và con người sống chung một cách hòa bình?', 'Colin Trevorrow', '147', 'the-gioi-khung-long.jpg', 'THẾ GIỚI KHỦNG LONG: LÃNH ĐỊA', '2022-06-22', '3y0KM5jUnmk');
INSERT INTO `cinema`.`movies` (`description`, `director`, `duration`, `image`, `name`, `start_date`, `trailer`) VALUES ('Cuộc gặp gỡ định mệnh giữa Trịnh Công Sơn và nữ sinh viên Nhật Bản Michiko tại Paris năm 1990 đã mở ra một mối duyên kỳ ngộ. Từ đây bắt đầu hành trình ngược dòng thời gian, khám phá tuổi thanh xuân và tình yêu của người nhạc sĩ tài hoa với các nàng thơ Thanh Thuý, Bích Diễm, Dao Ánh, Khánh Ly, và những tình khúc mà họ lưu lại trong trái tim ông. Bộ phim lãng mạn, mở ra thế giới nhạc Trịnh quyến rũ với những mảnh ghép tình yêu đa sắc, lung linh tuyệt đẹp.', 'Phan Gia Nhật Linh', '136', 'em-va-trinh.jpg', 'EM VÀ TRỊNH', '2022-06-17', 'zzik4JB9D1Q');
INSERT INTO `cinema`.`movies` (`description`, `director`, `duration`, `image`, `name`, `start_date`, `trailer`) VALUES ('Bộ phim khắc họa chân dung Trịnh Công Sơn từ một chàng thư sinh đa tài lãng tử trở thành “người nhạc sĩ viết tình ca hay nhất thế kỷ” với hàng trăm ca khúc về tình yêu và thân phận con người. Bộ phim “Trịnh Công Sơn” tràn đầy cảm hứng và nhiệt huyết của tuổi trẻ về người nhạc sĩ vĩ đại, đã sống, yêu và sáng tác trong một giai đoạn lịch sử của đất nước với tình yêu cứu rỗi, vượt lên mọi tan vỡ, khổ đau.', 'Phan Gia Nhật Linh', '95', 'trinh-cong-son.jpg', 'TRỊNH CÔNG SƠN', '2022-06-17 00:00:00', 'jCD7SDfme1A');
INSERT INTO `cinema`.`movies` (`description`, `director`, `duration`, `image`, `name`, `start_date`, `trailer`) VALUES ('Sau hơn ba mươi năm phục vụ, Pete “Maverick” Mitchell từng nổi danh là một phi công thử nghiệm quả cảm hàng đầu của Hải quân, né tránh cơ hội thăng chức, điều khiến anh cảm thấy bị bó buộc, để trở về làm chính mình.', 'Joseph Kosinski', '130', 'phi-cong-sieu-dang.jpg', 'PHI CÔNG SIÊU ĐẲNG MAVERICK', '2022-05-27', 'ZR99nOkEolM');
INSERT INTO `cinema`.`movies` (`description`, `director`, `duration`, `image`, `name`, `start_date`, `trailer`) VALUES ('Phần tiếp theo của loạt phim Harry Potter vẫn tiếp tục xoay quanh bộ ba Harry Potter - Ron Weasley - Hermione Granger. Bộ ba phù thủy sẽ đối mặt với một thử thách mới trong năm học thứ 2 tại trường Hogwarts. Một thế lực hắc ám đang bao trùm ngôi trường phù thủy này, tấn công hàng loạt học sinh và đe dọa mở Phòng Chứa Bí Mật một lần nữa. (Phim chiếu lại)', 'Chris Columbus', '161', 'harry-potter.jpg', 'HARRY POTTER VÀ CĂN PHÒNG BÍ MẬT (RE-RUN)', '2022-06-03', 'Cy4fjVMOwsY');
INSERT INTO `cinema`.`movies` (`description`, `director`, `duration`, `image`, `name`, `start_date`, `trailer`) VALUES ('Nobita tình cờ gặp được người ngoài hành tinh tí hon Papi, vốn là Tổng thống của hành tinh Pirika, chạy trốn tới Trái Đất để thoát khỏi những kẻ nổi loạn nơi quê nhà. Doraemon, Nobita và hội bạn thân dùng bảo bối đèn pin thu nhỏ biến đổi theo kích cỡ giống Papi để chơi cùng cậu bé. Thế nhưng, một tàu chiến không gian tấn công cả nhóm. Cảm thấy có trách nhiệm vì liên lụy mọi người, Papi quyết định một mình đương đầu với quân phiến loạn tàn ác. Doraemon và các bạn lên đường đến hành tinh Pirika, sát cánh bên người bạn của mình.', 'Yamaguchi Susumu', '109', 'doraemon.jpg', 'DORAEMON: NOBITA VÀ CUỘC CHIẾN VŨ TRỤ TÍ HON 2021', '2022-05-27', 'dd_R1GQwKlY');
INSERT INTO `cinema`.`movies` (`description`, `director`, `duration`, `image`, `name`, `start_date`, `trailer`) VALUES ('Hùng là cậu bé 8 tuổi mồ côi mẹ, sống với cha nhưng tình cảm cha con không khăng khít. Sau khi người bạn thân nhất của Hùng phải chuyển nhà, bố con cậu cũng bị chủ nhà ép chuyển đi. Cậu bé thường tìm kiếm niềm an ủi bằng cách ngắm bầu trời đêm. Một đêm có mưa sao băng, cậu thấy một ngôi sao rơi xuống vùng đất gần đó. Khi Hùng đi tìm, cậu không thấy ngôi sao nào mà thấy một cô bé. Hai đứa trẻ kết thân và giúp đỡ nhau.', 'Hàm Trần', '108', 'maika.jpg', 'MAIKA - CÔ BÉ ĐẾN TỪ HÀNH TINH KHÁC', '2022-05-27', 'mOH-VKJBsh8');
INSERT INTO `cinema`.`movies` (`description`, `director`, `duration`, `image`, `name`, `start_date`, `trailer`) VALUES ('Chuyến phiêu lưu đến Mặt Trăng của Peter bắt đầu khi em gái cậu, Anne, bị tên Trăng Tặc độc ác bắt cóc khi cô bé đang cố gắng giúp Bác Bọ Zoomzeman tìm lại vợ của mình. Trong cuộc hành trình đầy bất ngờ ấy, Peter gặp Thần Ngủ ở Đồng Cỏ Sao. Để giải cứu Anne, họ đã cùng nhau tham gia một cuộc đua kỳ thú dọc Dải Ngân Hà với 5 vị thần thiên nhiên: Ngài Bão Tố, Phù Thủy Sấm, Ngài Mưa Đá, Bậc Thầy Mưa Gió, và Bà Chúa Tuyết.', ' Ali Samadi Ahadi', '84', 'dai-nao-cung-trang.jpg', 'ĐẠI NÁO CUNG TRĂNG', '2022-06-03', 'i7TezW5eueI');
INSERT INTO `cinema`.`movies` (`description`, `director`, `duration`, `image`, `name`, `start_date`, `trailer`) VALUES ('Ngày xửa ngày xưa, có một cô bé mồ côi phải trở thành nàng công chúa bất đắc dĩ không giống ai. Một ngày nọ, hoàng tử bị một tên quan độc ác đầu độc và khiến Pil cùng những người bạn phải đứng lên bảo vệ mình và cả vương quốc.', 'Julien Fournet', '89', 'chuyen-phieu-luu-cua-pil.jpg', 'CHUYẾN PHIÊU LƯU CỦA PIL', '2022-06-01', 'yeGjaYJPM44');
INSERT INTO `cinema`.`movies` (`description`, `director`, `duration`, `image`, `name`, `start_date`, `trailer`) VALUES ('Chuyến leo núi thám hiểm của 2 người bạn thân nhanh chóng trở thanh cơn ác mộng khi bị 4 kẻ sát nhân truy đuổi. Chọn đường nào để sống sót khi trước mặt là vực thẳm và bọn truy sát đã bao vây mọi đường lui?', 'Howard J. Ford', '86', 'vuc-tham.jpg', 'VỰC THẲM', '2022-06-03', 'NSXZeTd6us8');
INSERT INTO `cinema`.`movies` (`description`, `director`, `duration`, `image`, `name`, `start_date`, `trailer`) VALUES ('Sau trận chiến ở Jaburo, lực lượng liên bang trái đất lên kế hoạch cho một chiến dịch đánh chiếm Odessa, trụ sở của Lực lượng tấn công Zeon. Tàu chiến White Base trên đường hướng đến Belfast để tiếp tế thì nhận được một mệnh lệnh mới: tìm đường đến hòn đảo được mệnh danh là Đảo Một Đi Không Trở Lại.', 'Yoshikazu Yasuhiko', '108', 'mobile-suit.jpg', 'MOBILE SUIT GUNDAM: CUCURUZ DOAN\'s ISLAND', '2022-06-03', 'oeSS3ZTt6MI');
INSERT INTO `cinema`.`movies` (`description`, `director`, `duration`, `image`, `name`, `start_date`, `trailer`) VALUES ('Sau các sự kiện của Avengers: Endgame, Tiến sĩ Stephen Strange tiếp tục nghiên cứu về Viên đá Thời gian. Nhưng một người bạn cũ đã trở thành kẻ thù tìm cách tiêu diệt mọi phù thủy trên Trái đất, làm xáo trộn kế hoạch của Strange và cũng khiến anh ta mở ra một tội ác khôn lường.', 'Sam Raimi', '126', 'phu-thuy-toi-thuong.jpg', 'PHÙ THỦY TỐI THƯỢNG TRONG ĐA VŨ TRỤ HỖN LOẠN', '2022-05-04', '3xccmeAsy8g');
INSERT INTO `cinema`.`movies` (`description`, `director`, `duration`, `image`, `name`, `start_date`, `trailer`) VALUES ('Câu chuyện bắt đầu khi Ellie, con gái của Keira mất tích. Sau nhiều lần báo cáo cảnh sát nhưng không có manh mối, Keira vô tình phát hiện ra con gái đang bị một thực thể cổ xưa bắt giữ trong chính ngôi nhà của mình. Liệu Keira có cứu được Ellie hay sẽ phải mất đi linh hồn của con mình mãi mãi?', 'Brendan Muldowney', '93', 'ham-khai-huyen.jpg', 'HẦM KHẢI HUYỀN', '2022-05-27', 'tgODAnBURak');
INSERT INTO `cinema`.`movies` (`description`, `director`, `duration`, `image`, `name`, `start_date`, `trailer`) VALUES ('Nối tiếp câu chuyện “Tình Người Duyên Ma” của nàng Nak - ma nữ nổi tiếng của người Thái với người chồng tên Mak, truyền thuyết cổ dựa trên những sự kiện lịch sử diễn ra từ thời vua Rama IV, Daeng là bộ phim kể về đứa bé ma do Nak sinh ra. Bộ phim xoay quanh cuộc sống của Daeng khi không có bố mẹ bên cạnh và tình bạn cũng như tình yêu với con người. Liệu cậu bé có được chào đón ở thế giới của con người hay phải đối diện với sự xa lánh, xua đuổi của dân làng như mẹ Nak?', 'Watcharapong Pattama', '96', 'daeng.jpg', 'DAENG – HẬU DUỆ “TÌNH NGƯỜI DUYÊN MA”', '2022-05-20', 'Yx6h_rgZrY8');
INSERT INTO `cinema`.`movies` (`description`, `director`, `duration`, `image`, `name`, `start_date`, `trailer`) VALUES ('Ông Thái là một cảnh sát về hưu nhưng không chịu an phận thủ thường, hàng ngày vẫn đi tìm bắt tội phạm vặt trong xóm cho đỡ nhớ nghề. Một ngày kia, Hoàng - tên trùm ma túy mới ra tù bỗng dưng chuyển đến xóm ông và mở một văn phòng bất động sản. Nghi ngờ đây là nơi làm ăn phi pháp, ông Thái quyết định âm thầm điều tra. Ông mua lại tiệm cơm tấm đối diện trụ sở của Hoàng để làm nơi theo dõi, đồng thời thu nạp Thu - Phú - Vinh - Mèo, đám thanh niên “bất hảo” trong xóm về quán hỗ trợ buôn bán để rảnh tay \"phá án\". Trớ trêu thay, tiệm cơm bất ngờ nổi tiếng và ăn nên làm ra, khiến cho \"chuyên án đặc biệt\" của ông đứng trước nguy cơ đổ bể.', 'Võ Thanh Hòa', '113', 'nghe-sieu-de.jpg', 'NGHỀ SIÊU DỄ', '2022-04-29', 'IOwvN-aoBpM');
INSERT INTO `cinema`.`movies` (`description`, `director`, `duration`, `image`, `name`, `start_date`, `trailer`) VALUES ('Bộ phim kể về chuyến hành trình hành động kết hợp khoa học viễn tưởng nhằm giới thiệu câu chuyện về nguồn gốc của nhân vật Buzz Lightyear — người anh hùng đã truyền cảm hứng sáng tạo ra đồ chơi. “Lightyear” sẽ theo chân Cảnh Sát Vũ Trụ huyền thoại trong cuộc hành trình bước ra ngoài không gian cùng với một nhóm chiến binh đầy tham vọng và người bạn đồng hành là chú mèo máy Sox.', 'Angus MacLane', '105', 'canh-sat-vu-tru.jpg', 'CẢNH SÁT VŨ TRỤ LIGHTYEAR', '2022-06-17', 'hB_JdXDnZVQ');
INSERT INTO `cinema`.`movies` (`description`, `director`, `duration`, `image`, `name`, `start_date`, `trailer`) VALUES ('Năm thứ ba của Harry Potter bắt đầu trở nên tồi tệ khi Harry phát hiện ra tên sát nhân Sirius Black đã trốn thoát khỏi nhà tù Azkaban và đang tìm đến Harry để trả thù. Một loạt cai ngục Azkaban được cử đến để bảo vệ Hogwarts và truy đuổi Sirius Black. Một giáo viên bí ẩn đã xuất hiện để dạy Harry Potter cách bảo vệ bản thân. Tuy nhiên, Harry dần phát hiện ra bí mật của mối quan hệ giữa Harry và tên sát nhân Sirius Black phức tạp hơn cậu nghĩ. (Re-run)', 'Alfonso Cuarón', '141', 'tu-nhan-azkban.jpg', 'HARRY POTTER VÀ TÙ NHÂN AZKABAN (RE-RUN)', '2022-06-17', 'q9-tAjeJ_nw');
INSERT INTO `cinema`.`movies` (`description`, `director`, `duration`, `image`, `name`, `start_date`, `trailer`) VALUES ('Finney Shaw, một cậu bé 13 tuổi nhút nhát nhưng thông minh, bị một kẻ giết người tàn bạo bắt cóc và nhốt trong một tầng hầm cách âm, nơi tiếng la hét trở nên vô ích. Khi một chiếc điện thoại bị ngắt kết nối trên tường bắt đầu đổ chuông, Finney phát hiện ra rằng cậu có thể nghe thấy giọng nói từ những nạn nhân trước đây của kẻ giết người. Và họ đã cố gắng đảm bảo rằng những gì đã xảy ra với họ không xảy ra với Finney.', 'Scott Derrickson', '150', 'dien-thoai-den.jpg', 'ĐIỆN THOẠI ĐEN', '2022-06-24', '5FdSkHJW884');
INSERT INTO `cinema`.`movies` (`description`, `director`, `duration`, `image`, `name`, `start_date`, `trailer`) VALUES ('Chuyện phim ELVIS khám phá những khía cạnh trong cuộc đời cũng như âm nhạc của Elvis Presley (Austin Butler) thông qua lăng kính về mối quan hệ phức tạp của ông với người quản lý Tom Parker (Tom Hanks). Được kể từ góc nhìn của Parker, phim đào sâu vào sự liên kết của Presley và Parker trong suốt 20 năm, từ lúc cậu trai trẻ Presley vụt sáng thành sao trong bối cảnh xã hội Mỹ rối ren và văn hóa đại chúng ngày một phát triển. Trung tâm của hành trình đó là một trong những người có ảnh hưởng sâu sắc nhất trong cuộc đời của Elvis, Priscilla Presley (Olivia DeJonge).', 'Baz Luhrmann', '160', 'elvis.jpg', 'ELVIS', '2022-06-24', 'r5KmbYkCxJo');
INSERT INTO `cinema`.`movies` (`description`, `director`, `duration`, `image`, `name`, `start_date`, `trailer`) VALUES ('Sang-hyun (Song Kang Ho) là chủ một cửa tiệm giặt ủi ngập đầu trong nợ nần. Dong-soo (Gang Dong Won) – từng là trẻ mồ côi và hiện đang làm việc cho một cơ sở vận hành “chiếc hộp em bé”. Vào một đêm mưa gió, Sang-hyun và Dong-soo lén lút mang đi một đứa bé vừa bị bỏ rơi trong hộp. Trớ trêu thay, bà mẹ trẻ So-young (Lee Ji Eun) đột nhiên đổi ý và quay trở lại tìm con mình. Dù bán tín bán nghi, So-young quyết định tham gia vào chuyến đi kỳ lạ tìm kiếm gia đình mới cho chính con mình. Trong lúc đó, nữ cảnh sát Soo-jin (Doona Bae) cùng cấp dưới của mình, cảnh sát Lee (Lee Joo Young) đã luôn theo sát và chứng kiến toàn bộ quá trình. Họ lặng lẽ theo dõi bộ ba để thu thập những bằng chứng mang tính quyết định. Cuộc hành trình bám theo những người môi giới của các thanh tra sẽ diễn biến theo một chiều hướng mà chính họ cũng không thể lường trước được. Tất cả mọi chuyện đều bắt đầu từ “chiếc hộp em bé”.', 'Kore-eda Hirokazu', '100', 'nguoi-moi-gioi.jpg', 'NGƯỜI MÔI GIỚI', '2022-06-24', 'bHQHazW5uLM');
INSERT INTO `cinema`.`movies` (`description`, `director`, `duration`, `image`, `name`, `start_date`, `trailer`) VALUES ('Đội quân Ruy Băng Đỏ đã bị Son Goku tiêu diệt. Thế nhưng, những kẻ kế nghiệp của chúng đã tạo ra hai chiến binh Android mới là Gamma 1 và Gamma 2. Hai Android này tự nhận mình là “Siêu anh hùng”. Chúng bắt đầu tấn công Piccolo và Gohan… Mục tiêu của Đội quân Ruy Băng Đỏ mới này là gì? Trước nguy cơ cận kề, đã đến lúc các siêu anh hùng thực thụ phải thức tỉnh!', 'Tetsuro Kodama', '100', 'dragon.jpg', 'Dragon Ball Super: SUPER HERO', '2022-06-24', 'C9KHj81O_L0');
INSERT INTO `cinema`.`movies` (`description`, `director`, `duration`, `image`, `name`, `start_date`, `trailer`) VALUES ('Hành trình phiêu lưu của #Gru song hành cùng với #Otto và viên đá của ác nhân MINIONS: SỰ TRỖI DẬY CỦA GRU - DCKC: 2022', 'Kyle Balda, Brad Ableson, Jonathan del Val', '120', 'minions.jpg', 'MINIONS: SỰ TRỖI DẬY CỦA GRU', '2022-07-01', 'dTQXlDV16SY');
INSERT INTO `cinema`.`movies` (`description`, `director`, `duration`, `image`, `name`, `start_date`, `trailer`) VALUES ('Vốn từng là một chiến binh hùng mạnh của Asgard, trải qua vô số trận chiến lớn nhỏ nhưng sau sự kiện trong Avengers: Endgame (2019) cùng vô số mất mát, Thần Sấm không còn muốn theo đuổi con đường siêu anh hùng. Từ đây, anh lên đường tìm ra ý nghĩa của cuộc sống và nhìn nhận lại bản thân mình.', 'Taika Waititi', '120', 'tinh-yeu-va-sam-set.jpg', 'THOR: TÌNH YÊU VÀ SẤM SÉT', '2022-07-08', 'UBgPypHGAqE');
INSERT INTO `cinema`.`movies` (`description`, `director`, `duration`, `image`, `name`, `start_date`, `trailer`) VALUES ('Pororo và những người bạn tìm thấy chú khủng long nhỏ Alo đang ngủ say trong chiếc phi thuyền hình quả trứng. Alo không nhớ gì ngoài tên của mình. Khi Pororo và bạn bè giúp Alo sửa phi thuyền thì phi thuyền vụt sáng và biến mất cùng Alo và người bạn của Pororo là Crong. Pororo đuổi theo chiếc phi thuyền đến Đảo Khủng Long và chạm trán với Mr.Y, kẻ chuyên bắt cóc khủng long để bán cho người ngoài hành tinh. Để giải cứu bạn của mình, Pororo phải vượt qua nỗi sợ khủng long để chiến đấu với người ngoài hành tinh và đội quân người máy của Mr.Y.', 'Kim Hyunho, Yoon Jewan', '100', 'pororo.jpg', 'PORORO: CUỘC PHIÊU LƯU ĐẾN ĐẢO KHỦNG LONG', '2022-07-15', '4dxVVwLSPlA');
INSERT INTO `cinema`.`movies` (`description`, `director`, `duration`, `image`, `name`, `start_date`, `trailer`) VALUES ('Một thanh tra cảnh sát rơi vào lưới tình với goá phụ trẻ - nghi phạm giết người trong vụ án mà anh ta đang điều tra.', 'Park Chan Wook', '120', 'quyet-tam-chia-tay.jpg', 'QUYẾT TÂM CHIA TAY', '2022-07-15', 'jY1RvoXEGjM');
INSERT INTO `cinema`.`movies` (`description`, `director`, `duration`, `image`, `name`, `start_date`, `trailer`) VALUES ('Tại Shibuya náo nhiệt mùa Halloween, Thiếu úy Sato Miwako khoác lên mình chiếc váy cưới tinh khôi trong tiệc cưới như cổ tích, và người đàn ông bên cạnh cô không ai khác ngoài Trung sĩ Takagi Wataru. Trong giây phút trọng đại, một nhóm người xấu ập vào tấn công, Trung sĩ Takagi liều mình bảo vệ Sato. Anh tai qua nạn khỏi, nhưng Sato chết lặng khi nhìn thấy bóng ma Thần Chết trong giây phút sinh tử của Takagi. Điều này khiến cô nhớ lại cái chết của đồng nghiệp, cũng là người cô từng yêu trước đây, Thanh tra Matsuda Jinpei. Cùng lúc này, hung thủ của vụ đánh bom liên tiếp mà Matsuda điều tra năm xưa đã vượt ngục thành công. Khi Conan tìm đến Furuya Rei (hay Amuro Toru), người bạn cùng khóa với Matsuda, cậu được nghe câu chuyện liên quan đến vụ đánh bom với kẻ thủ ác mang bí danh \"Plamya\". Hôn lễ nguy hiểm nhất thế giới, buổi dạ hành đẫm máu tại Shibuya vào đêm Halloween sắp sửa bắt đầu.', 'Gosho Aoyama, Susumu Mitsunaka', '110', 'conan.jpg', 'THÁM TỬ LỪNG DANH CONAN: NÀNG DÂU HALLOWEEN', '2022-07-22', 'iSn8PzOtDcI');
INSERT INTO `cinema`.`movies` (`description`, `director`, `duration`, `image`, `name`, `start_date`, `trailer`) VALUES ('Quân, một dân chơi miệt vườn với tài “sát gái” thượng hạng, bỗng một ngày phải gánh lấy \"cục nợ con rơi\" từ bạn gái cũ. Được sự trợ giúp \"ba phần đắc lực bảy phần phá đám\" của Tám Mánh, Quân dần mất hết hy vọng tìm lại mẹ cho đứa bé và dần trở thành người cha hoàn hảo trong mắt Bé Thỏ. Cuộc sống đầy sắc màu và tiếng cười của hai cha con bị đặt trước thử thách lớn lao khi người mẹ mà Bé Thỏ ngày đêm mong ngóng cuối cùng cũng xuất hiện…', 'Huỳnh Đông', '120', 'dan-choi.jpg', 'DÂN CHƠI KHÔNG SỢ CON RƠI', '2022-07-29', 'm18gn36U5no');
INSERT INTO `cinema`.`movies` (`description`, `director`, `duration`, `image`, `name`, `start_date`, `trailer`) VALUES ('Trong “Liên Minh Siêu Thú DC”, Siêu Cún Krypto và Superman là cặp bài trùng không thể tách rời, cùng sở hữu những siêu năng lực tương tự và cùng nhau chiến đấu chống lại tội phạm tại thành phố Metropolis. Khi Superman và những thành viên của Liên Minh Công Lý bị bắt cóc, Krypto phải thuyết phục cậu chàng Ace luộm thuộm, nàng Heo PB, Rùa Merton và Sóc Chip khai phá những sức mạnh tiềm ẩn và cùng nhau giải cứu các siêu anh hùng. “Liên Minh Siêu Thú DC” có sự góp giọng của bộ đôi ngôi sao nổi tiếng bậc nhất Hollywood Dwayne Johnson (lồng tiếng cho Siêu cún Krypto) và Kevin Hart (Superman). Đặc biệt, tài tử Keanu Reeves sẽ đảm nhận những câu thoại chất lừ đến từ Batman.', 'Jared Stern', '120', 'lien-minh-sieu-thu.jpg', 'LIÊN MINH SIÊU THÚ DC', '2022-07-29', 'L2umMe5uRnk');
INSERT INTO `cinema`.`movies` (`description`, `director`, `duration`, `image`, `name`, `start_date`, `trailer`) VALUES ('Ladybug (Brad Pitt) - một sát thủ lành nghề vừa trở lại sau khoảng thời gian nghỉ hưu. Anh nhận nhiệm vụ từ một phụ nữ bí ẩn là thu hồi chiếc vali trên chuyến tàu cao tốc ở Nhật Bản. Những tưởng đây sẽ là phi vụ dễ ăn thì một loạt biến cố ập đến. Ladybug phải đối mặt với vô số thế lực khác nhau trên chiếc tàu hỏa cùng nhắm vào chiếc vali kia. Đối thủ của anh lần lượt là Lemon (Brian Tyree Henry), Kimura (Andrew Koji), Hornet (Zazie Beetz), Prince (Joey King) và Tangerine (Aaron Taylor-Johnson). Mỗi người đều có những âm mưu và cách thức hoạt động riêng dẫn đến một cục diện vô cùng rối ren.', 'David Leitch', '150', 'sat-thu-doi-dau.jpg', 'SÁT THỦ ĐỐI ĐẦU', '2022-08-12', '6tabT850jMA');
INSERT INTO `cinema`.`movies` (`description`, `director`, `duration`, `image`, `name`, `start_date`, `trailer`) VALUES ('Bộ phim kể về Kya Clark - một cô gái bị gia đình bỏ rơi, lớn lên ở vùng đầm lầy phía nam thị trấn Barkley Cove vào những năm 50. Khi cảnh sát của thị trấn bị phát hiện đã qua đời, người ta bắt đầu dồn mọi mối nghi ngờ vào Kya', 'Olivia Newman', '110', 'xa-ngoai-kia.jpg', 'XA NGOÀI KIA NƠI LOÀI TÔM HÁT', '2022-09-02', 'S2jTTbz_hVs');

-- data rooms
INSERT INTO `cinema`.`rooms` (`name`, `status`) VALUES ('01', b'1');
INSERT INTO `cinema`.`rooms` (`name`, `status`) VALUES ('02', b'1');
INSERT INTO `cinema`.`rooms` (`name`, `status`) VALUES ('03', b'1');
INSERT INTO `cinema`.`rooms` (`name`, `status`) VALUES ('04', b'1');

-- data schedules
INSERT INTO `cinema`.`schedules` (`datetime`, `movie_id`, `room_id`) VALUES ('2022-06-20 9:00', '1', '1');
INSERT INTO `cinema`.`schedules` (`datetime`, `movie_id`, `room_id`) VALUES ('2022-06-20 15:30', '1', '2');
INSERT INTO `cinema`.`schedules` (`datetime`, `movie_id`, `room_id`) VALUES ('2022-06-20 18:30', '1', '3');
INSERT INTO `cinema`.`schedules` (`datetime`, `movie_id`, `room_id`) VALUES ('2022-06-21 9:30', '1', '4');
INSERT INTO `cinema`.`schedules` (`datetime`, `movie_id`, `room_id`) VALUES ('2022-06-21 13:00', '1', '1');
INSERT INTO `cinema`.`schedules` (`datetime`, `movie_id`, `room_id`) VALUES ('2022-06-21 9:00', '1', '2');
INSERT INTO `cinema`.`schedules` (`datetime`, `movie_id`, `room_id`) VALUES ('2022-06-22 10:00', '1', '3');
INSERT INTO `cinema`.`schedules` (`datetime`, `movie_id`, `room_id`) VALUES ('2022-06-22 13:30', '1', '4');
INSERT INTO `cinema`.`schedules` (`datetime`, `movie_id`, `room_id`) VALUES ('2022-06-22 19:30', '1', '1');
INSERT INTO `cinema`.`schedules` (`datetime`, `movie_id`, `room_id`) VALUES ('2022-06-20 9:00', '2', '2');
INSERT INTO `cinema`.`schedules` (`datetime`, `movie_id`, `room_id`) VALUES ('2022-06-20 15:30', '2', '3');
INSERT INTO `cinema`.`schedules` (`datetime`, `movie_id`, `room_id`) VALUES ('2022-06-20 18:30', '2', '4');
INSERT INTO `cinema`.`schedules` (`datetime`, `movie_id`, `room_id`) VALUES ('2022-06-21 9:30', '2', '1');
INSERT INTO `cinema`.`schedules` (`datetime`, `movie_id`, `room_id`) VALUES ('2022-06-21 13:00', '2', '2');
INSERT INTO `cinema`.`schedules` (`datetime`, `movie_id`, `room_id`) VALUES ('2022-06-21 9:00', '2', '3');
INSERT INTO `cinema`.`schedules` (`datetime`, `movie_id`, `room_id`) VALUES ('2022-06-22 10:00', '2', '4');
INSERT INTO `cinema`.`schedules` (`datetime`, `movie_id`, `room_id`) VALUES ('2022-06-22 13:30', '2', '1');
INSERT INTO `cinema`.`schedules` (`datetime`, `movie_id`, `room_id`) VALUES ('2022-06-22 19:30', '2', '2');
INSERT INTO `cinema`.`schedules` (`datetime`, `movie_id`, `room_id`) VALUES ('2022-06-20 9:00', '3', '3');
INSERT INTO `cinema`.`schedules` (`datetime`, `movie_id`, `room_id`) VALUES ('2022-06-20 15:30', '3', '4');
INSERT INTO `cinema`.`schedules` (`datetime`, `movie_id`, `room_id`) VALUES ('2022-06-20 18:30', '3', '1');
INSERT INTO `cinema`.`schedules` (`datetime`, `movie_id`, `room_id`) VALUES ('2022-06-21 9:30', '3', '2');
INSERT INTO `cinema`.`schedules` (`datetime`, `movie_id`, `room_id`) VALUES ('2022-06-21 13:00', '3', '3');
INSERT INTO `cinema`.`schedules` (`datetime`, `movie_id`, `room_id`) VALUES ('2022-06-21 9:00', '3', '4');
INSERT INTO `cinema`.`schedules` (`datetime`, `movie_id`, `room_id`) VALUES ('2022-06-22 10:00', '3', '1');
INSERT INTO `cinema`.`schedules` (`datetime`, `movie_id`, `room_id`) VALUES ('2022-06-22 13:30', '3', '2');
INSERT INTO `cinema`.`schedules` (`datetime`, `movie_id`, `room_id`) VALUES ('2022-06-22 19:30', '3', '3');
INSERT INTO `cinema`.`schedules` (`datetime`, `movie_id`, `room_id`) VALUES ('2022-06-18 15:30', '2', '1');
INSERT INTO `cinema`.`schedules` (`datetime`, `movie_id`, `room_id`) VALUES ('2022-06-18 18:30', '2', '1');
INSERT INTO `cinema`.`schedules` (`datetime`, `movie_id`, `room_id`) VALUES ('2022-06-18 9:30', '3', '2');
INSERT INTO `cinema`.`schedules` (`datetime`, `movie_id`, `room_id`) VALUES ('2022-06-18 13:00', '3', '2');
INSERT INTO `cinema`.`schedules` (`datetime`, `movie_id`, `room_id`) VALUES ('2022-06-18 18:00', '3', '4');
INSERT INTO `cinema`.`schedules` (`datetime`, `movie_id`, `room_id`) VALUES ('2022-06-20 18:30', '4', '1');
INSERT INTO `cinema`.`schedules` (`datetime`, `movie_id`, `room_id`) VALUES ('2022-06-20 20:00', '4', '1');
INSERT INTO `cinema`.`schedules` (`datetime`, `movie_id`, `room_id`) VALUES ('2022-06-20 9:00', '5', '2');
INSERT INTO `cinema`.`schedules` (`datetime`, `movie_id`, `room_id`) VALUES ('2022-06-20 10:30', '5', '1');
INSERT INTO `cinema`.`schedules` (`datetime`, `movie_id`, `room_id`) VALUES ('2022-06-20 12:00', '6', '3');
INSERT INTO `cinema`.`schedules` (`datetime`, `movie_id`, `room_id`) VALUES ('2022-06-19 9:00', '6', '4');
INSERT INTO `cinema`.`schedules` (`datetime`, `movie_id`, `room_id`) VALUES ('2022-06-19 13:00', '7', '1');

-- data tickets
INSERT INTO `cinema`.`tickets` (`price`, `schedule_id`) VALUES ('75000', '1');
INSERT INTO `cinema`.`tickets` (`price`, `schedule_id`) VALUES ('75000', '2');
INSERT INTO `cinema`.`tickets` (`price`, `schedule_id`) VALUES ('75000', '3');
INSERT INTO `cinema`.`tickets` (`price`, `schedule_id`) VALUES ('75000', '4');
INSERT INTO `cinema`.`tickets` (`price`, `schedule_id`) VALUES ('75000', '5');
INSERT INTO `cinema`.`tickets` (`price`, `schedule_id`) VALUES ('75000', '6');
INSERT INTO `cinema`.`tickets` (`price`, `schedule_id`) VALUES ('75000', '7');
INSERT INTO `cinema`.`tickets` (`price`, `schedule_id`) VALUES ('75000', '8');
INSERT INTO `cinema`.`tickets` (`price`, `schedule_id`) VALUES ('75000', '9');
INSERT INTO `cinema`.`tickets` (`price`, `schedule_id`) VALUES ('75000', '10');
INSERT INTO `cinema`.`tickets` (`price`, `schedule_id`) VALUES ('75000', '11');
INSERT INTO `cinema`.`tickets` (`price`, `schedule_id`) VALUES ('75000', '12');
INSERT INTO `cinema`.`tickets` (`price`, `schedule_id`) VALUES ('75000', '13');

-- data seats
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('A01', b'1', '1');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('A02', b'1', '1');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('A03', b'1', '1');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('A04', b'1', '1');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('A05', b'1', '1');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('A06', b'1', '1');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('A07', b'1', '1');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('A08', b'1', '1');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('A09', b'1', '1');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('A10', b'1', '1');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('B01', b'1', '1');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('B02', b'1', '1');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('B03', b'1', '1');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('B04', b'1', '1');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('B05', b'1', '1');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('B06', b'1', '1');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('B07', b'1', '1');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('B08', b'1', '1');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('B09', b'1', '1');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('B10', b'1', '1');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('C01', b'1', '1');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('C02', b'1', '1');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('C03', b'1', '1');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('C04', b'1', '1');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('C05', b'1', '1');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('C06', b'1', '1');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('C07', b'1', '1');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('C08', b'1', '1');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('C09', b'1', '1');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('C10', b'1', '1');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('D01', b'1', '1');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('D02', b'1', '1');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('D03', b'1', '1');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('D04', b'1', '1');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('D05', b'1', '1');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('D06', b'1', '1');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('D07', b'1', '1');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('D08', b'1', '1');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('D09', b'1', '1');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('D10', b'1', '1');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('E01', b'1', '1');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('E02', b'1', '1');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('E03', b'1', '1');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('E04', b'1', '1');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('E05', b'1', '1');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('E06', b'1', '1');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('E07', b'1', '1');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('E08', b'1', '1');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('E09', b'1', '1');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('E10', b'1', '1');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('F01', b'1', '1');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('F02', b'1', '1');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('F03', b'1', '1');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('F04', b'1', '1');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('F05', b'1', '1');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('F06', b'1', '1');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('F07', b'1', '1');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('F08', b'1', '1');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('F09', b'1', '1');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('F10', b'1', '1');

INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('A01', b'1', '2');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('A02', b'1', '2');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('A03', b'1', '2');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('A04', b'1', '2');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('A05', b'1', '2');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('A06', b'1', '2');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('A07', b'1', '2');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('A08', b'1', '2');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('A09', b'1', '2');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('A10', b'1', '2');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('B01', b'1', '2');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('B02', b'1', '2');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('B03', b'1', '2');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('B04', b'1', '2');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('B05', b'1', '2');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('B06', b'1', '2');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('B07', b'1', '2');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('B08', b'1', '2');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('B09', b'1', '2');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('B10', b'1', '2');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('C01', b'1', '2');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('C02', b'1', '2');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('C03', b'1', '2');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('C04', b'1', '2');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('C05', b'1', '2');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('C06', b'1', '2');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('C07', b'1', '2');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('C08', b'1', '2');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('C09', b'1', '2');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('C10', b'1', '2');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('D01', b'1', '2');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('D02', b'1', '2');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('D03', b'1', '2');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('D04', b'1', '2');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('D05', b'1', '2');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('D06', b'1', '2');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('D07', b'1', '2');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('D08', b'1', '2');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('D09', b'1', '2');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('D10', b'1', '2');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('E01', b'1', '2');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('E02', b'1', '2');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('E03', b'1', '2');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('E04', b'1', '2');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('E05', b'1', '2');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('E06', b'1', '2');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('E07', b'1', '2');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('E08', b'1', '2');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('E09', b'1', '2');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('E10', b'1', '2');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('F01', b'1', '2');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('F02', b'1', '2');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('F03', b'1', '2');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('F04', b'1', '2');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('F05', b'1', '2');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('F06', b'1', '2');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('F07', b'1', '2');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('F08', b'1', '2');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('F09', b'1', '2');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('F10', b'1', '2');

INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('A01', b'1', '10');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('A02', b'1', '10');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('A03', b'1', '10');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('A04', b'1', '10');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('A05', b'1', '10');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('A06', b'1', '10');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('A07', b'1', '10');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('A08', b'1', '10');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('A09', b'1', '10');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('A10', b'1', '10');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('B01', b'1', '10');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('B02', b'1', '10');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('B03', b'1', '10');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('B04', b'1', '10');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('B05', b'1', '10');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('B06', b'1', '10');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('B07', b'1', '10');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('B08', b'1', '10');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('B09', b'1', '10');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('B10', b'1', '10');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('C01', b'1', '10');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('C02', b'1', '10');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('C03', b'1', '10');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('C04', b'1', '10');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('C05', b'1', '10');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('C06', b'1', '10');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('C07', b'1', '10');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('C08', b'1', '10');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('C09', b'1', '10');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('C10', b'1', '10');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('D01', b'1', '10');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('D02', b'1', '10');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('D03', b'1', '10');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('D04', b'1', '10');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('D05', b'1', '10');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('D06', b'1', '10');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('D07', b'1', '10');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('D08', b'1', '10');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('D09', b'1', '10');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('D10', b'1', '10');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('E01', b'1', '10');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('E02', b'1', '10');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('E03', b'1', '10');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('E04', b'1', '10');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('E05', b'1', '10');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('E06', b'1', '10');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('E07', b'1', '10');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('E08', b'1', '10');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('E09', b'1', '10');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('E10', b'1', '10');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('F01', b'1', '10');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('F02', b'1', '10');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('F03', b'1', '10');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('F04', b'1', '10');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('F05', b'1', '10');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('F06', b'1', '10');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('F07', b'1', '10');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('F08', b'1', '10');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('F09', b'1', '10');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('F10', b'1', '10');

INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('A01', b'1', '11');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('A02', b'1', '11');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('A03', b'1', '11');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('A04', b'1', '11');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('A05', b'1', '11');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('A06', b'1', '11');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('A07', b'1', '11');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('A08', b'1', '11');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('A09', b'1', '11');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('A10', b'1', '11');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('B01', b'1', '11');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('B02', b'1', '11');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('B03', b'1', '11');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('B04', b'1', '11');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('B05', b'1', '11');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('B06', b'1', '11');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('B07', b'1', '11');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('B08', b'1', '11');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('B09', b'1', '11');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('B10', b'1', '11');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('C01', b'1', '11');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('C02', b'1', '11');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('C03', b'1', '11');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('C04', b'1', '11');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('C05', b'1', '11');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('C06', b'1', '11');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('C07', b'1', '11');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('C08', b'1', '11');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('C09', b'1', '11');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('C10', b'1', '11');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('D01', b'1', '11');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('D02', b'1', '11');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('D03', b'1', '11');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('D04', b'1', '11');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('D05', b'1', '11');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('D06', b'1', '11');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('D07', b'1', '11');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('D08', b'1', '11');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('D09', b'1', '11');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('D10', b'1', '11');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('E01', b'1', '11');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('E02', b'1', '11');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('E03', b'1', '11');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('E04', b'1', '11');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('E05', b'1', '11');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('E06', b'1', '11');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('E07', b'1', '11');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('E08', b'1', '11');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('E09', b'1', '11');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('E10', b'1', '11');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('F01', b'1', '11');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('F02', b'1', '11');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('F03', b'1', '11');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('F04', b'1', '11');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('F05', b'1', '11');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('F06', b'1', '11');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('F07', b'1', '11');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('F08', b'1', '11');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('F09', b'1', '11');
INSERT INTO `cinema`.`seats` (`name`, `status`, `schedule_id`) VALUES ('F10', b'1', '11');

-- data booking_details
INSERT INTO `cinema`.`booking_details` (`booking_id`, `seat_id`, `ticket_id`) VALUES ('1', '16', '8');
INSERT INTO `cinema`.`booking_details` (`booking_id`, `seat_id`, `ticket_id`) VALUES ('1', '17', '8');
INSERT INTO `cinema`.`booking_details` (`booking_id`, `seat_id`, `ticket_id`) VALUES ('1', '18', '8');
INSERT INTO `cinema`.`booking_details` (`booking_id`, `seat_id`, `ticket_id`) VALUES ('2', '25', '8');
INSERT INTO `cinema`.`booking_details` (`booking_id`, `seat_id`, `ticket_id`) VALUES ('3', '20', '8');
INSERT INTO `cinema`.`booking_details` (`booking_id`, `seat_id`, `ticket_id`) VALUES ('3', '21', '8');
